twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
        assets/images: images
    globals:
        twig_asset_image_directory: '%asset_image_directory%'
        stripe_publishable_key: '%env(resolve:STRIPE_PUBLIC_KEY)%'