version: '3.6'
services:
  mysql:
    image: mysql
    volumes:
      - ./build/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=kalitics
      - MYSQL_PASSWORD=kalitics
      - MYSQL_DATABASE=kalitics
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8080:80'
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
