version: "3.5"

services:
    front:
        restart: always
        image: nginx
        volumes:
            - ./:/var/www:ro
            - ./var/nginx:/var/log/nginx:rw
            # http://symfony.com/doc/current/setup/web_server_configuration.html#nginx
            - ./docker/front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80

    engine:
        restart: always
        container_name: hibooengine
        build:
            context: .
        env_file:
            - .env
        networks:
            - default # this network
        volumes:
            - $HOME/.composer:/.composer:rw,cached
            - $HOME/.ssh:/root/.ssh:rw,cached
            - .:/var/www:rw,cached
            - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./var/sessions/engine:/root:rw
        environment:
            PHP_IDE_CONFIG: serverName=hiboo

    database:
        restart: always
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=hiboo
            - MYSQL_USER=hiboouser
            - MYSQL_PASSWORD=X0145Hiboo
            - MYSQL_ROOT_PASSWORD=R0145Hiboo
            - TZ=Europe/Paris
        volumes:
            - ./var/data:/var/lib/mysql:rw
            - ./var/dumps:/var/dumps:rw
            - ./var/sessions/mysql:/root:rw
        expose:
            - "3306"

    redis:
        restart: always
        image: redis:3.2.8

    mailcatcher:
        restart: always
        image: schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:1025 #DISABLE ON PROD

networks:
    default: # this network
        driver: bridge
