<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9BKQNeJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9BKQNeJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9BKQNeJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9BKQNeJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9BKQNeJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9BKQNeJ',
    'container.build_id' => 'a3887a17',
    'container.build_time' => 1591479904,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9BKQNeJ');
